
project_id = "jwblwuzihcozkfwuarzu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.create-checkout]
verify_jwt = true
[functions.check-subscription]
verify_jwt = true
[functions.customer-portal]
verify_jwt = true
