// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nafhtovonxmvddrnvpzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZmh0b3ZvbnhtdmRkcm52cHpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzIzNTUsImV4cCI6MjA2MTEwODM1NX0.CrRVDF1OmO-LRXCXpkF_Xf4lYJO88VFENRABx0UmVLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);