// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwblwuzihcozkfwuarzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3Ymx3dXppaGNvemtmd3Vhcnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NjEzNDcsImV4cCI6MjA2MTUzNzM0N30.PywHzNf2ONsdHH84yXDWDBgQVSSAQj6v_-MThF8Ywwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);